In [5]:
import numpy as np
from dig4bio.io import read_raman_file
from dig4bio.constants import LABEL_COLUMNS, FINGERPRINT_GRID

In [3]:
df = read_raman_file('source_datasets.csv','processed',subfolder='source_grid_fingerprint_linear')

In [4]:
df.sample(10)

               300           301           302  ...  MSM_present  fold_idx    device
970    5520.918455   5522.875000   5460.375000  ...          0.0         3   metrohm
183    3012.400000   3015.575000   3018.750000  ...          0.0         3  anton532
1720   2352.467306   2375.968219   2345.445949  ...          0.0         4       tec
605    3847.286500   3828.930700   3811.728900  ...          0.0         2    kaiser
53     3377.720000   3384.820000   3391.920000  ...          0.0         1  anton532
2038  21631.293967  21551.956825  21479.857686  ...          0.0         2   tornado
1471   2348.803543   2370.001446   2336.059450  ...          0.0         1       tec
1365   2351.951404   2367.319772   2337.063371  ...          1.0         0       tec
144    3256.360000   3252.035000   3247.710000  ...          1.0         2  anton532
2253  38302.323029  38139.751307  37977.253209  ...          0.0         4   tornado

[10 rows x 1507 columns]

In [10]:
mean_= np.mean(df[LABEL_COLUMNS].to_numpy(),axis=0)
mean_

array([3.00951504, 0.63980571, 1.04713309])

In [24]:
x= df[FINGERPRINT_GRID.astype(str)]
x

               300           301  ...         1799         1800
0      2964.060000   2960.900000  ...  1147.840000  1131.170000
1      2930.550000   2932.180000  ...  1128.430000  1116.740000
2      2934.220000   2933.090000  ...  1121.680000  1107.380000
3      2900.720000   2899.225000  ...  1109.675000  1098.530000
4      2909.560000   2910.130000  ...  1107.105000  1091.940000
...            ...           ...  ...          ...          ...
2256  19834.726356  19755.366726  ...  2520.730018  2554.243570
2257  19801.862213  19746.414903  ...  2556.665152  2562.910425
2258  19787.656895  19713.836514  ...  2551.553859  2574.883732
2259  19772.745131  19663.747217  ...  2565.363886  2553.838800
2260  19849.309644  19807.086344  ...  2537.302495  2527.507457

[2261 rows x 1501 columns]

In [27]:
predictions = np.tile(mean_,(len(x),1))
predictions

array([[3.00951504, 0.63980571, 1.04713309],
       [3.00951504, 0.63980571, 1.04713309],
       [3.00951504, 0.63980571, 1.04713309],
       ...,
       [3.00951504, 0.63980571, 1.04713309],
       [3.00951504, 0.63980571, 1.04713309],
       [3.00951504, 0.63980571, 1.04713309]], shape=(2261, 3))